### ISSUE TITLE
Create website color palette

### ISSUE THREAD

**Issue by hannamlittlefield** [GreenField-Org/CMMechanical#1]
- Using the [C&M website ](https://www.cmmhvac.com/) create a color palette with hex codes
- Red should be a  tertiary color (used for anchor tag or buttons)

**Comment by greenervigil** [comment]
Primary: #25368A
Secondary: #009CE0
Tertiary: #FF0000

Red: #E70000
Text:  #1A1C20
background/Text on Dark:  #F9F9F9
