### ISSUE TITLE
Create repo and boilerplate 

### ISSUE THREAD

**Issue by hannamlittlefield** [GreenField-Org/CMMechanical#8]
- Set up new repository with NextJS boilerplate 
- Inside the repo, create the folder structure for each page titled with each page name

- [x] About Us
- [x] Services 
- [x] Mitsubishi Products
- [x] NYSERDA Program
- [x] FAQ

- Create a default page.tsx for each page 
- set up dev env in code sandbox off main branch.

**Comment by greenervigil** [comment]
https://codesandbox.io/p/github/GreenField-Org/CMMechanical/main?file=%2F.codesandbox%2Ftasks.json%3A1%2C1&workspaceId=588ab6a2-2599-4e24-bd6e-df85e12879bc
